# Generated by Django 4.2.5 on 2023-09-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulette', '0002_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='round',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='round',
            name='cells',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='round',
            name='cells',
            field=models.ManyToManyField(blank=True, null=True, to='roulette.cell'),
        ),
    ]
