# Generated by Django 4.2.5 on 2023-09-07 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roulette', '0003_cell_remove_round_logs_remove_round_cells_delete_log_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Round',
            new_name='Game',
        ),
    ]
