# Generated by Django 4.2.5 on 2023-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_rename_round_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
