# Generated by Django 4.2.5 on 2023-09-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_game_is_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cells',
        ),
        migrations.AddField(
            model_name='cell',
            name='cells',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roulette.game'),
        ),
    ]
