# Generated by Django 4.2.5 on 2023-09-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_remove_game_cells_cell_cells'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='cells',
            new_name='game',
        ),
    ]
